# Deploy Next.js to Shared Hosting - Secrets ready
name: Deploy Next.js to Shared Hosting


on:
  push:
    branches:
      - main  # або назва вашої головної гілки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Server
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: out/
          remote_path: /home/ferry436/domains/ferrymano.top/public_html/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 22
